# Generated by Django 4.2.5 on 2023-09-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('CPF', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('Senha', models.CharField(max_length=512)),
                ('SenhaProvisoria', models.CharField(blank=True, max_length=512, null=True)),
                ('Nome', models.CharField(max_length=255)),
                ('Cargo', models.CharField(max_length=50)),
                ('NivelAcesso', models.CharField(max_length=50)),
                ('NivelOrganizacional', models.CharField(max_length=50)),
                ('DataNascimento', models.DateField()),
                ('DataIngresso', models.DateField()),
                ('Email', models.EmailField(max_length=225, unique=True)),
                ('Celular', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
