# Generated by Django 4.2.5 on 2023-09-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='SenhaProvisoriaData',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
