# Generated by Django 4.2.5 on 2023-09-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_customuser_senha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Cargo',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Celular',
            new_name='celular',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='CPF',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='DataIngresso',
            new_name='data_ingresso',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='DataNascimento',
            new_name='data_nascimento',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='NivelAcesso',
            new_name='nivel_acesso',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='NivelOrganizacional',
            new_name='nivel_organizacional',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='SenhaProvisoria',
            new_name='senha_provisoria',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='SenhaProvisoriaData',
            new_name='senha_provisoria_data',
        ),
    ]
